on:
  push:
    branches:
      - master
  release:
    types: [ published ]

env:
  MINVERBUILDMETADATA: build.${{github.run_number}}

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
      - name: Build
        run: dotnet build -c Release
      - name: Pack
        run: dotnet pack -c Release --output nupkgs --no-build
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latest
          path: ./nupkgs/*.nupkg
  
  push-guthub:
    name: Push GitHub Nuget
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'release'
    environment:
      name: "GitHub"
      url: https://github.com/${{ github.repository }}/packages
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: latest
      - name: Dotnet NuGet Add Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: Dotnet NuGet Push
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GH_PACKAGES_TOKEN }} --source github --skip-duplicate