on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
      - name: Build
        run: dotnet build -c Release
      - name: Pack
        run: dotnet pack -c Release --output nupkgs --no-build
      - name: Publish Artifacts
        run: actions/upload-artifacts@v4
        with:
          name: latest
          path: ./nupkgs/*.nupkg